<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-android</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <SupportedOSPlatformVersion>26.0</SupportedOSPlatformVersion>
    <ApplicationId>com.gasukinani.stride.editor</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>

    <!-- Pinapayagan ang unsafe code na kailangan ng graphics engine -->
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <!-- Dito pumapasok ang Stride Engine -->
  <ItemGroup>
    <PackageReference Include="Stride.Engine" Version="4.2.0.2232" />
    <PackageReference Include="Stride.Graphics" Version="4.2.0.2232" />
    <PackageReference Include="Stride.Navigation" Version="4.2.0.2232" />
    <PackageReference Include="Stride.Physics" Version="4.2.0.2232" />
  </ItemGroup>
</Project>
